### ISSUE TITLE
fixWebpackSourcePaths throws an error

### ISSUE THREAD

**Issue by elbrus** [mattlewis92/karma-coverage-istanbul-reporter#15]
I'm using Windows 7, didn't try in other OS.

Removed some not required info and here it is, what I have.

Dev dependencies:
```
	"istanbul-instrumenter-loader": "2.0.0",
	"jasmine-core": "2.6.1",
	"karma": "1.6.0",
	"karma-chrome-launcher": "2.0.0",
	"karma-coverage-istanbul-reporter": "1.2.0",
	"karma-jasmine": "1.1.0",
	"karma-sinon": "1.0.5",
	"karma-sourcemap-loader": "0.3.7",
	"karma-webpack": "2.0.3",
	"react": "15.3.0",
	"react-addons-test-utils": "15.3.0",
	"react-dom": "15.3.0",
	"react-hot-loader": "1.3.0",
	"sinon": "2.1.0",
	"webpack": "2.4.1",
	"webpack-dev-server": "2.4.4",
	"webpack-hot-middleware": "2.18.0"
```

Karma config:
```
module.exports = function(config) {
	config.set({
		frameworks: ['jasmine', 'sinon'],
		files: [testFiles],
		plugins: [
			'karma-jasmine',
			'karma-sinon',
			'karma-webpack',
			'karma-coverage-istanbul-reporter',
			'karma-spec-reporter',
			'karma-chrome-launcher',
			'karma-sourcemap-loader'
		],
		browsers: ['Chrome'],
		preprocessors: {
			[testFiles]: ['webpack', 'sourcemap']
		},
		reporters: ['spec', 'coverage-istanbul'],
		coverageIstanbulReporter: {
			reports: ['text-summary', 'html'],
			dir: path.resolve(__dirname, '../tests-code-coverage'),
			fixWebpackSourcePaths: true,
			skipFilesWithNoCoverage: true,
			'report-config': {
				html: {
					subdir: '.'
				}
			}
		},
		webpack: webpackConfig
	});
};
```

Webpack config:
```
module.exports = {
	resolve: {
		extensions: ['.js', '.scss', '.css', '.json'],
		modules: ['node_modules', 'src']
	},
	resolveLoader: {
		moduleExtensions: ['-loader'],
		modules: ['web_loaders', 'web_modules', 'node_loaders', 'node_modules', 'webpack_loaders']
	},
	devtool: 'inline-source-map',
	module: {
		rules: [{
			test: /\.(js|jsx)$/,
			use: ['react-hot', 'babel'],
			include: jsInclude
		}, {
			test: /\.(js|jsx)$/,
			enforce: 'post',
			include: path.resolve(__dirname, '../src'),
			loader: 'istanbul-instrumenter',
			options: {
				esModules: true
			}
		]
	}
};
```

Here is an error I'm getting:
```
ERROR [karma]: TypeError: Cannot read property 'map' of undefined
    at Object.fixWebpackSourcePaths (..\karma-coverage-istanbul-reporter\src\util.js:22:31)
    at Object.keys.forEach.filename (..\karma-coverage-istanbul-reporter\src\reporter.js:64:46)
```

I'm not sure is it related or not, but here is a sample of HTML reporter:
![clipboard02](https://cloud.githubusercontent.com/assets/2395165/25566600/cc98a522-2de4-11e7-9e55-7537c907f648.jpg)

* 1st line shows missed else statement, and I have lots of files with the same thing, but else statement doesn't exist at that point
* this component is 100% covered, but numbers are way off

**Comment by mattlewis92** [comment]
I've just pushed 1.2.1 with a fix for the error you're encountering. The coverage issues in the file aren't related to this lib though as it's just a tiny wrapper over the [istanbul-api](https://github.com/istanbuljs/istanbuljs) which does all the heavy lifting. As you're a babel user though you can just ditch the istanbul-instrumenter-loader and instead use the [istanbul babel plugin](https://github.com/istanbuljs/babel-plugin-istanbul) which will give you much better reporting as there are no sourcemaps involved, instead the actual source is instrumented. Hope that helps! 😄
