### ISSUE TITLE
Unable to find source file

### ISSUE THREAD

**Issue by zaun** [mattlewis92/karma-coverage-istanbul-reporter#2]
The filename being generated is `background.vue?1e26b24c.html` and it's contents is the following error:

```
Unable to lookup source: /Users/juzaun/Development/sagely-sign-web/src/components/background.vue?1e26b24c(ENOENT: no such file or directory, open '/Users/juzaun/Development/sagely-sign-web/src/components/background.vue?1e26b24c')
Error: Unable to lookup source: /Users/juzaun/Development/sagely-sign-web/src/components/background.vue?1e26b24c(ENOENT: no such file or directory, open '/Users/juzaun/Development/sagely-sign-web/src/components/background.vue?1e26b24c')
  at Context.defaultSourceLookup [as sourceFinder] (/Users/juzaun/Development/sagely-sign-web/node_modules/istanbul-lib-report/lib/context.js:15:15)
  at Context.getSource (/Users/juzaun/Development/sagely-sign-web/node_modules/istanbul-lib-report/lib/context.js:74:17)
  at Object.annotateSourceCode (/Users/juzaun/Development/sagely-sign-web/node_modules/istanbul-reports/lib/html/annotator.js:175:38)
  at HtmlReport.onDetail (/Users/juzaun/Development/sagely-sign-web/node_modules/istanbul-reports/lib/html/index.js:217:39)
  at Visitor.(anonymous function) [as onDetail] (/Users/juzaun/Development/sagely-sign-web/node_modules/istanbul-lib-report/lib/tree.js:34:30)
  at ReportNode.Node.visit (/Users/juzaun/Development/sagely-sign-web/node_modules/istanbul-lib-report/lib/tree.js:123:17)
  at /Users/juzaun/Development/sagely-sign-web/node_modules/istanbul-lib-report/lib/tree.js:116:23
  at Array.forEach (native)
  at visitChildren (/Users/juzaun/Development/sagely-sign-web/node_modules/istanbul-lib-report/lib/tree.js:115:32)
  at ReportNode.Node.visit (/Users/juzaun/Development/sagely-sign-web/node_modules/istanbul-lib-report/lib/tree.js:126:5)
  at /Users/juzaun/Development/sagely-sign-web/node_modules/istanbul-lib-report/lib/tree.js:116:23
  at Array.forEach (native)
  at visitChildren (/Users/juzaun/Development/sagely-sign-web/node_modules/istanbul-lib-report/lib/tree.js:115:32)
  at ReportNode.Node.visit (/Users/juzaun/Development/sagely-sign-web/node_modules/istanbul-lib-report/lib/tree.js:126:5)
  at Tree.visit (/Users/juzaun/Development/sagely-sign-web/node_modules/istanbul-lib-report/lib/tree.js:158:20)
  at /Users/juzaun/Development/sagely-sign-web/node_modules/istanbul-api/lib/reporter.js:84:18
  at Array.forEach (native)
  at Object.write (/Users/juzaun/Development/sagely-sign-web/node_modules/istanbul-api/lib/reporter.js:82:35)
  at browsers.forEach.browser (/Users/juzaun/Development/sagely-sign-web/node_modules/karma-coverage-istanbul-reporter/src/reporter.js:57:16)
  at Array.forEach (native)
  at Collection.forEach (/Users/juzaun/Development/sagely-sign-web/node_modules/karma/lib/browser_collection.js:93:21)
  at CoverageIstanbulReporter.onRunComplete (/Users/juzaun/Development/sagely-sign-web/node_modules/karma-coverage-istanbul-reporter/src/reporter.js:26:14)
  at Server. (/Users/juzaun/Development/sagely-sign-web/node_modules/karma/lib/events.js:13:22)
  at emitTwo (events.js:111:20)
  at Server.emit (events.js:191:7)
  at emitRunCompleteIfAllBrowsersDone (/Users/juzaun/Development/sagely-sign-web/node_modules/karma/lib/server.js:259:12)
  at Server. (/Users/juzaun/Development/sagely-sign-web/node_modules/karma/lib/server.js:281:9)
  at emitTwo (events.js:111:20)
  at Server.emit (events.js:191:7)
  at Browser.onComplete (/Users/juzaun/Development/sagely-sign-web/node_modules/karma/lib/browser.js:142:13)
  at Socket. (/Users/juzaun/Development/sagely-sign-web/node_modules/karma/lib/events.js:13:22)
  at emitTwo (events.js:111:20)
  at Socket.emit (events.js:191:7)
  at /Users/juzaun/Development/sagely-sign-web/node_modules/socket.io/lib/socket.js:503:12
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickCallback (internal/process/next_tick.js:98:9)
```

Basically it's adding a hash to the filename so it can't find it on disk. My webpack config is:

```
  {
    module: {
      rules: [{
        test: /\.js$/,
        exclude: /node_modules\//,
        loader: 'babel-loader',
        options: babelOptions
      }, {
        test: /\.styl$/,
        loaders: ['style-loader', 'css-loader', 'stylus-loader']
      }, {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: {
          loaders: {
            js: 'babel-loader?' + JSON.stringify(babelOptions)
          },
          postLoaders: {
            js: 'istanbul-instrumenter-loader?esModules=true'
          }
        }
      }, {
        include: /\.json$/,
        loaders: ['json-loader']
      }, {
        enforce: 'post',
        test: /\.js$/,
        exclude: /node_modules|test\//,
        loader: 'istanbul-instrumenter-loader',
        query: {
          esModules: true
        }
      }]
    },
    resolve: {
      modules: ['node_modules'],
      alias: {vue: 'vue/dist/vue.js'}
    }
  }
```

Inside the `vue-loader` I'm trying to instrument the javascript. This is causing the issue I think. Any way to solve this? If there is anything else I can get to help or try let me know.

**Comment by zaun** [comment]
I think this fixes it. I'm still running tests.

```
        if (fileCoverage.inputSourceMap && coverageIstanbulReporter.fixWebpackSourcePaths) {
          fileCoverage.inputSourceMap.sources = fileCoverage.inputSourceMap.sources.map(source => {
            var ret = source;
            if (ret.indexOf('!') !== -1) {
              ret = ret.split('!').pop();
            }
            if (ret.indexOf('?') !== -1) {
              ret = source.split('?').shift();
            }
            return ret;
          });
        }
```

**Comment by mattlewis92** [comment]
Fixed by https://github.com/mattlewis92/karma-coverage-istanbul-reporter/pull/3
