### ISSUE TITLE
lcov report error with new 1.3.1 release

### ISSUE THREAD

**Issue by mistyharsh** [mattlewis92/karma-coverage-istanbul-reporter#33]
Thanks for this great reporter.

## Problem Summary:
After upgrading my dependency to `1.3.1` from `1.3.0`, **lcov** coverage is broken.

## Details Description:
After upgrading, my test commands are running fine without any error. However, my coverage files contain errors:
```
Unable to lookup source: /home/harshal/monjin/data/src/home/harshal/monjin/data/src/jsonapi/function.ts(ENOENT: no such file or directory, open '/home/harshal/monjin/data/src/home/harshal/monjin/data/src/jsonapi/function.ts')
Error: Unable to lookup source: /home/harshal/monjin/data/src/home/harshal/monjin/data/src/jsonapi/function.ts(ENOENT: no such file or directory, open '/home/harshal/monjin/data/src/home/harshal/monjin/data/src/jsonapi/function.ts')
    at Context.defaultSourceLookup [as sourceFinder] (/home/harshal/monjin/data/node_modules/istanbul-lib-report/lib/context.js:15:15)
    at Context.getSource (/home/harshal/monjin/data/node_modules/istanbul-lib-report/lib/context.js:74:17)
    at Object.annotateSourceCode (/home/harshal/monjin/data/node_modules/istanbul-reports/lib/html/annotator.js:172:38)
    at HtmlReport.onDetail (/home/harshal/monjin/data/node_modules/istanbul-reports/lib/html/index.js:217:39)
    at Visitor.(anonymous function) [as onDetail] (/home/harshal/monjin/data/node_modules/istanbul-lib-report/lib/tree.js:34:30)
    at ReportNode.Node.visit (/home/harshal/monjin/data/node_modules/istanbul-lib-report/lib/tree.js:123:17)
    at /home/harshal/monjin/data/node_modules/istanbul-lib-report/lib/tree.js:116:23
    at Array.forEach (<anonymous>)
    at visitChildren (/home/harshal/monjin/data/node_modules/istanbul-lib-report/lib/tree.js:115:32)
    at ReportNode.Node.visit (/home/harshal/monjin/data/node_modules/istanbul-lib-report/lib/tree.js:126:5)
    at /home/harshal/monjin/data/node_modules/istanbul-lib-report/lib/tree.js:116:23
    at Array.forEach (<anonymous>)
    at visitChildren (/home/harshal/monjin/data/node_modules/istanbul-lib-report/lib/tree.js:115:32)
    at ReportNode.Node.visit (/home/harshal/monjin/data/node_modules/istanbul-lib-report/lib/tree.js:126:5)
    at Tree.visit (/home/harshal/monjin/data/node_modules/istanbul-lib-report/lib/tree.js:158:20)
    at /home/harshal/monjin/data/node_modules/istanbul-api/lib/reporter.js:84:18
```

## My Karma configuration:
```
const webpackConfig = require('./webpack.config');

delete webpackConfig.entry;
delete webpackConfig.output;
delete webpackConfig.plugins;

webpackConfig.devtool = 'inline-source-map';
webpackConfig.module.rules.push({
    test: /\.(j|t)s$/,
    enforce: 'post',
    use: {
        loader: 'istanbul-instrumenter-loader',
        options: {
            esModules: true
        }
    },
    exclude: /node_modules/
});

module.exports = function(config) {
    config.set({
        basePath: '.',

        frameworks: ['mocha'],

        files: [
            'test/jsonapi/where.ts'
        ],

        // list of files to exclude
        exclude: [],

        // preprocess matching files before serving them to the browser
        preprocessors: {
            'src/**/*.ts': ['webpack', 'sourcemap'],
            'test/**/*.ts': ['webpack', 'sourcemap'],
        },

        mime: {
            'text/x-typescript': ['ts','tsx']
        },

        webpack: webpackConfig,
        webpackMiddleware: {
            noInfo: true
        },

        reporters: ['progress', 'coverage-istanbul'],

        coverageIstanbulReporter: {
            dir: 'coverage',
            reports: [ 'text-summary', 'html' ],
            fixWebpackSourcePaths: true
        },

        // web server port
        port: 9876,
    })
}

```
## My webpack configuration:
```
const path = require('path');

const PATHS = {
    src: path.join(__dirname, './src'),
    dist: path.join(__dirname, './dist/lib')
};

module.exports = {
    context: PATHS.src,
    devtool: 'source-map',

    entry: {
        main: './main.ts'
    },
    output: {
        filename: 'data.js',
        path: PATHS.dist,
    },

    module: {
        rules: [
            {
                test: /\.tsx?$/,
                loader: 'awesome-typescript-loader',
                exclude: /node_modules/
            }
        ]
    },
    plugins: [],
    resolve: {
        extensions: ['.tsx', '.ts', '.jsx', '.js', '.json'],
        mainFields: ['module', 'main']
    }

};
```

Not sure if this is related to: #32.
Please let me know how can I help?

**Comment by mattlewis92** [comment]
Oops, so sorry about that! Would you be so kind as to [edit this line](https://github.com/mattlewis92/karma-coverage-istanbul-reporter/blob/master/src/util.js#L28) in the reporters source and add `console.log(webpackConfig.context, sourceMap.sourceRoot)` and let me know the output. Thanks! 😄

**Comment by mistyharsh** [comment]
Sure, I can do that. Here is the output:
```
/home/harshal/monjin/data/src /home/harshal/monjin/data/
/home/harshal/monjin/data/src /home/harshal/monjin/data/
/home/harshal/monjin/data/src /home/harshal/monjin/data/
/home/harshal/monjin/data/src /home/harshal/monjin/data/
/home/harshal/monjin/data/src /home/harshal/monjin/data/
/home/harshal/monjin/data/src /home/harshal/monjin/data/
/home/harshal/monjin/data/src /home/harshal/monjin/data/
/home/harshal/monjin/data/src /home/harshal/monjin/data/
/home/harshal/monjin/data/src /home/harshal/monjin/data/
```

**Comment by mattlewis92** [comment]
That's perfect, thank you. I can see what's wrong now, 1.3.2 incoming 😄
