### ISSUE TITLE
Regression in 2.0.3: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by web-padawan** [mattlewis92/karma-coverage-istanbul-reporter#55]
After upgrading to 2.0.3 which includes #10, I started getting the following error in AppVeyor:
```
07 09 2018 21:28:06.411:ERROR [karma]: TypeError: Cannot read property 'replace' of undefined
    at fixPathSeparators (C:\projects\lit-components\node_modules\karma-coverage-istanbul-reporter\src\util.js:20:21)
    at Object.fixWebpackSourcePaths (C:\projects\lit-components\node_modules\karma-coverage-istanbul-reporter\src\util.js:39:16)
    at Object.keys.forEach.filename (C:\projects\lit-components\node_modules\karma-coverage-istanbul-reporter\src\reporter.js:46:44)
    at Array.forEach (<anonymous>)
    at addCoverage (C:\projects\lit-components\node_modules\karma-coverage-istanbul-reporter\src\reporter.js:43:27)
    at browserOrBrowsers.forEach.browser (C:\projects\lit-components\node_modules\karma-coverage-istanbul-reporter\src\reporter.js:96:44)
    at Array.forEach (<anonymous>)
    at BrowserCollection.forEach (C:\projects\lit-components\node_modules\karma\lib\browser_collection.js:81:26)
    at createReport (C:\projects\lit-components\node_modules\karma-coverage-istanbul-reporter\src\reporter.js:96:25)
    at CoverageIstanbulReporter.onRunComplete (C:\projects\lit-components\node_modules\karma-coverage-istanbul-reporter\src\reporter.js:210:7)
    at Server.<anonymous> (C:\projects\lit-components\node_modules\karma\lib\events.js:40:26)
    at emitTwo (events.js:131:20)
    at Server.emit (events.js:214:7)
    at emitRunCompleteIfAllBrowsersDone (C:\projects\lit-components\node_modules\karma\lib\server.js:257:14)
    at Server.<anonymous> (C:\projects\lit-components\node_modules\karma\lib\server.js:286:9)
    at emitOne (events.js:116:13)
npm ERR! Test failed.  See above for more details.
```

Full build log: https://ci.appveyor.com/project/web-padawan/lit-components/build/18

Fixed in my project by removing the `fixWebpackSourcePaths` setting (it wasn't actually needed).

**Comment by mattlewis92** [comment]
Thanks for the bug report, this is now fixed in `2.0.4` 😄
